# Generated by Django 3.2.12 on 2022-03-22 13:21

import ckeditor.fields
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_learn_video',
            name='sort_description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tax_learn_video',
            name='sub_category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tax_learn_video',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tax_learn_video',
            name='unique_sub_category_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tax_learn_video',
            name='video_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='video_url_category/video_image/'),
        ),
        migrations.AlterField(
            model_name='tax_learn_video',
            name='with_unique_sub_sub_category_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
