# Generated by Django 3.2.12 on 2022-03-23 10:44

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220322_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_page_reviews1',
            name='more_About_page_header_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='more_detail_page/reviews/images'),
        ),
        migrations.AlterField(
            model_name='tax_planner_2_question_answer',
            name='tax_plan_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
