# Generated by Django 3.2.11 on 2022-04-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220323_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_page_reviews1',
            name='more_About_page_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='more_detail_page/reviews/images'),
        ),
        migrations.AlterField(
            model_name='manualform16',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='form-16-pdf/'),
        ),
        migrations.AlterField(
            model_name='service_page_reviews',
            name='review_image',
            field=models.ImageField(null=True, upload_to='service_page_reviews/review_image/'),
        ),
        migrations.AlterField(
            model_name='tax_learn_video',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to='video_url_category/video_image/'),
        ),
        migrations.AlterField(
            model_name='xmlfile',
            name='xmlfile',
            field=models.FileField(upload_to='xml_files'),
        ),
    ]
