# Generated by Django 3.2.12 on 2022-03-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_tax_planner_2_question_answer',
            name='tax_plan_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
