# Generated by Django 3.2.12 on 2022-03-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_tax_planner_2_question_answer_tax_plan_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business_gst_dahsboard_registrations',
            options={'verbose_name': 'gst-dahsboard registrations Without XML Registration'},
        ),
        migrations.AlterModelOptions(
            name='business_gst_dashbaord_super_user_registrations',
            options={'verbose_name': 'gst-dashbaord-super-user-registrations without XML Registration'},
        ),
        migrations.AlterModelOptions(
            name='business_gst_dashboard_checklist_selectbox',
            options={'verbose_name': 'gst-dashboard-checklist-selectbox'},
        ),
        migrations.AlterModelOptions(
            name='business_gst_dashboard_checklist_selectbox_main_data',
            options={'verbose_name': ' gst checklist-selectbox-data'},
        ),
    ]
