# Generated by Django 3.2.12 on 2022-03-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_topic',
            options={'verbose_name': 'FAQ"s main heading like Frequently Asked Question '},
        ),
        migrations.AlterModelOptions(
            name='product_home',
            options={'verbose_name': 'Production Home Page dropdown links'},
        ),
        migrations.AlterModelOptions(
            name='review_database',
            options={'verbose_name': 'FAQ"s question and answer '},
        ),
    ]
