# Generated by Django 3.2.11 on 2022-04-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220324_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_plan',
            name='pr_img1',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pricing_plan',
            name='pr_img2',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pricing_plan',
            name='pr_img3',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
