# Generated by Django 3.2.12 on 2022-03-23 07:11

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_wagtail', '0002_auto_20220317_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_image1',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='wagtail_image/'),
        ),
        migrations.AddField(
            model_name='leftsidehomepage',
            name='title_image1',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='wagtail_image/'),
        ),
        migrations.AddField(
            model_name='leftsidewithstickynotehomepage',
            name='title_image1',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='wagtail_image/'),
        ),
        migrations.AddField(
            model_name='rightsidehomepage',
            name='title_image1',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='wagtail_image/'),
        ),
    ]
