# Generated by Django 3.2.12 on 2022-03-16 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='abouts_us_page_heading_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_des', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('main_heading', models.CharField(blank=True, choices=[('heading', 'Main heading ')], default=None, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'About us page section 3',
            },
        ),
        migrations.CreateModel(
            name='blog_categories_and_Sub_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Blog category ',
            },
        ),
        migrations.CreateModel(
            name='bussiness_popular_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buss_popular_item_group', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_item', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_plan_name', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_plan_sort_name', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_plan_id', models.CharField(max_length=500, unique=True)),
                ('buss_popular_regullar_price', models.IntegerField(default=None, null=True)),
                ('buss_popular_discount', models.IntegerField(default=None, null=True)),
                ('buss_popular_gst', models.IntegerField(default=None, null=True)),
                ('buss_popular_total_discount', models.IntegerField(default=None, null=True)),
                ('buss_popular_our_price', models.IntegerField(default=None, null=True)),
                ('buss_popular_total_gst', models.IntegerField(default=None, null=True)),
                ('buss_popular_total_price_and_gst', models.IntegerField(default=None, null=True)),
                ('buss_popular_duration', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_plan_detail1', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_plan_detail2', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_plan_detail3', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_plan_detail4', models.CharField(default=None, max_length=500, null=True)),
                ('buss_popular_pr_img1', models.ImageField(blank=True, null=True, upload_to='bussiness_popular_plan/preferred_plan_image1/')),
                ('buss_popular_pr_img2', models.ImageField(blank=True, null=True, upload_to='bussiness_popular_plan/preferred_plan_image2/')),
                ('buss_popular_pr_img3', models.ImageField(blank=True, null=True, upload_to='bussiness_popular_plan/preferred_plan_image3/')),
            ],
            options={
                'verbose_name': 'Business Popular plans',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact us data',
            },
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_col', models.CharField(blank=True, max_length=100000, null=True)),
                ('title_name', models.CharField(blank=True, max_length=100000, null=True)),
                ('title_link', models.CharField(blank=True, max_length=100000, null=True)),
            ],
            options={
                'verbose_name': 'Footer page data',
            },
        ),
        migrations.CreateModel(
            name='Get_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('option', models.CharField(max_length=50)),
                ('mobile_input', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Get Quote data',
            },
        ),
        migrations.CreateModel(
            name='google_login_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Google Login id',
            },
        ),
        migrations.CreateModel(
            name='individual_popular_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_popular_item_group', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_item', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_plan_name', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_plan_sort_name', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_plan_id', models.CharField(max_length=500, unique=True)),
                ('ind_popular_regullar_price', models.IntegerField(default=None, null=True)),
                ('ind_popular_discount', models.IntegerField(default=None, null=True)),
                ('ind_popular_gst', models.IntegerField(default=None, null=True)),
                ('ind_popular_total_discount', models.IntegerField(default=None, null=True)),
                ('ind_popular_our_price', models.IntegerField(default=None, null=True)),
                ('ind_popular_total_gst', models.IntegerField(default=None, null=True)),
                ('ind_popular_total_price_and_gst', models.IntegerField(default=None, null=True)),
                ('ind_popular_duration', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_plan_detail1', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_plan_detail2', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_plan_detail3', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_plan_detail4', models.CharField(default=None, max_length=500, null=True)),
                ('ind_popular_pr_img1', models.ImageField(blank=True, null=True, upload_to='individual_popular_plan/preferred_plan_image1/')),
                ('ind_popular_pr_img2', models.ImageField(blank=True, null=True, upload_to='individual_popular_plan/preferred_plan_image2/')),
                ('ind_popular_pr_img3', models.ImageField(blank=True, null=True, upload_to='individual_popular_plan/preferred_plan_image3/')),
            ],
            options={
                'verbose_name': 'Indivisual popular plans',
            },
        ),
        migrations.CreateModel(
            name='main_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myorder_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sailer_account', models.CharField(blank=True, max_length=5000, null=True)),
                ('sailer_bank_acc_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('sailer_address', models.TextField(blank=True, max_length=5000, null=True)),
                ('sailer_acc_ifsc_code', models.CharField(blank=True, max_length=5000, null=True)),
                ('sailer_acc_holder_name', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'myorder invoice for buyer',
            },
        ),
        migrations.CreateModel(
            name='popular_and_recent_blog_lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_blog_url', models.CharField(max_length=1000)),
                ('blog_category', models.CharField(choices=[('POPULAR', 'popular blog list'), ('RECENT', 'recent blog list')], max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Popular and recent blog categories',
            },
        ),
        migrations.CreateModel(
            name='Pricing_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group', models.CharField(default=None, max_length=500, null=True)),
                ('item', models.CharField(default=None, max_length=500, null=True)),
                ('plan_name', models.CharField(default=None, max_length=500, null=True)),
                ('plan_sort_name', models.CharField(default=None, max_length=500, null=True)),
                ('plan_id', models.CharField(max_length=500, unique=True)),
                ('regullar_price', models.IntegerField(default=None, null=True)),
                ('discount', models.IntegerField(default=None, null=True)),
                ('gst', models.IntegerField(default=None, null=True)),
                ('total_discount', models.IntegerField(default=None, null=True)),
                ('our_price', models.IntegerField(default=None, null=True)),
                ('total_gst', models.IntegerField(default=None, null=True)),
                ('total_price_and_gst', models.IntegerField(default=None, null=True)),
                ('duration', models.CharField(default=None, max_length=500, null=True)),
                ('plan_detail1', models.CharField(default=None, max_length=500, null=True)),
                ('plan_detail2', models.CharField(default=None, max_length=500, null=True)),
                ('plan_detail3', models.CharField(default=None, max_length=500, null=True)),
                ('plan_detail4', models.CharField(default=None, max_length=500, null=True)),
                ('pr_img1', models.ImageField(blank=True, null=True, upload_to='pricing_plan_image/preferred_plan_image1/')),
                ('pr_img2', models.ImageField(blank=True, null=True, upload_to='pricing_plan_image/preferred_plan_image2/')),
                ('pr_img3', models.ImageField(blank=True, null=True, upload_to='pricing_plan_image/preferred_plan_image3/')),
            ],
            options={
                'verbose_name': 'All plans details',
            },
        ),
        migrations.CreateModel(
            name='product_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_link_title', models.CharField(blank=True, choices=[('ABC', 'Absolute Compliance '), ('KDC', 'Knowledge Center'), ('TXP', 'Tax Planner')], max_length=3, null=True)),
                ('title_url', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Production Home Page',
            },
        ),
        migrations.CreateModel(
            name='review_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=100000, null=True)),
                ('answer', models.CharField(blank=True, max_length=100000, null=True)),
            ],
            options={
                'verbose_name': 'plan buy reviews data like question and answer',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('contact_number', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default=None, max_length=100000, null=True)),
                ('fname', models.CharField(blank=True, default=None, max_length=100000, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=100000, null=True)),
                ('order_id', models.CharField(blank=True, max_length=10000, null=True, unique=True)),
                ('plan_id', models.CharField(default=None, max_length=10000, null=True)),
                ('total_plan', models.CharField(default=None, max_length=10000, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('gstin', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('company_add', models.CharField(blank=True, default=None, max_length=100000, null=True)),
                ('pin_code', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('pricing_plan_ind', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pricing_plan_buss', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('made_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('pricing_plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pricing_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_user_name', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('plan_id', models.CharField(default=None, max_length=100, null=True)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(default=None, max_length=100, null=True)),
                ('state', models.CharField(default=None, max_length=200, null=True)),
                ('order_id', models.CharField(default=None, max_length=2000, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('gstin', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('company_add', models.CharField(blank=True, default=None, max_length=100000, null=True)),
                ('pin_code', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pricing_plan')),
                ('pricing_plan_buss', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bussiness_popular_plan')),
                ('pricing_plan_ind', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.individual_popular_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blog_categories_and_Sub_categories_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categories', models.CharField(default=None, max_length=5000)),
                ('sub_categories_links', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('main_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.blog_categories_and_sub_categories')),
            ],
            options={
                'verbose_name': 'main category and sub category in blog pages ',
            },
        ),
    ]
