# Generated by Django 3.2.12 on 2022-03-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('home_wagtail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blog_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.blog_categories_and_sub_categories_sub'),
        ),
        migrations.AlterField(
            model_name='leftsidehomepage',
            name='blog_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.blog_categories_and_sub_categories_sub'),
        ),
        migrations.AlterField(
            model_name='leftsidewithstickynotehomepage',
            name='blog_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.blog_categories_and_sub_categories_sub'),
        ),
        migrations.AlterField(
            model_name='rightsidehomepage',
            name='blog_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.blog_categories_and_sub_categories_sub'),
        ),
        migrations.AlterField(
            model_name='rightsidewithstickynotehomepage',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.blog_categories_and_sub_categories'),
        ),
    ]
